syntax = "proto3";

option csharp_namespace = "UserService.Protos";

package user;

service UserGrpc {
  rpc GetUserById (UserIdRequest) returns (UserResponse);
  rpc GetUserByName (UserNameRequest) returns (UserResponse);
  rpc VerifyCredentials (VerifyCredentialsRequest) returns (VerifyCredentialsResponse);
}

message UserIdRequest {
  int32 id = 1;
}

message UserNameRequest {
  string username = 1;
}

message UserResponse {
  int32 id = 1;
  string username = 2;
  string email = 3;
  string createdAt = 4;
  reserved 5;
  reserved "passwordHash";
  repeated string roles = 6;
}

message VerifyCredentialsRequest {
  string username = 1;
  string password = 2;
}

message VerifyCredentialsResponse {
  bool success = 1;
  UserResponse user = 2;
}
