<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.3" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
    <ProjectReference Include="..\TMApi.Contracts\TMApi.Contracts.csproj" />
  </ItemGroup>
</Project>